# Generated by Django 2.1.1 on 2018-09-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickeruser',
            name='groups',
            field=models.ManyToManyField(help_text='Groups this user belongs too', to='photos.Group'),
        ),
    ]
