# Generated by Django 2.1.1 on 2018-09-23 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_flickeruser_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='flicker_user',
            new_name='created_by',
        ),
    ]
