# Generated by Django 2.1.1 on 2018-09-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20180923_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='flicker_user',
            new_name='commented_by',
        ),
    ]
