# Generated by Django 2.1.1 on 2018-09-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20180923_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='comment',
            new_name='note',
        ),
    ]
