# Generated by Django 2.1.1 on 2018-09-24 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20180923_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flickerusergroup',
            name='flicker_user',
        ),
        migrations.RemoveField(
            model_name='flickerusergroup',
            name='group',
        ),
        migrations.AlterField(
            model_name='flickeruser',
            name='nsid',
            field=models.CharField(db_index=True, help_text='NSID of the user', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='flickeruser',
            name='user',
            field=models.OneToOneField(help_text='User related to the flicker user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='nsid',
            field=models.CharField(db_index=True, help_text='NSID of the group', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='nsid',
            field=models.CharField(db_index=True, help_text='NSID of the photo', max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='FlickerUserGroup',
        ),
    ]
